### ISSUE TITLE
Errors when starting to debug

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-python-debugger#143]
Testing #141

Debugging started fine, but I got this error in the terminal. It was repeated multiple times

```
roblou@robfast:/datadrive/testext2$  /usr/bin/env /usr/bin/python3.9 /home/roblou/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13271006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 40923 -- /datadrive/testext2/test.py
E+00000.070: Error while enumerating installed packages.

             Traceback (most recent call last):
               File "/home/roblou/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13271006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'

             Stack where logged:
               File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "/home/roblou/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13271006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 91, in <module>
                 main()
               File "/home/roblou/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13271006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 21, in main
                 log.describe_environment("debugpy.launcher startup environment:")
               File "/home/roblou/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13271006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "/home/roblou/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13271006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "/home/roblou/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13271006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
```

**Comment by md3356** [comment]
I encounter the same question, did u solve it?

**Comment by simonbrady** [comment]
I get this with `v2024.0.0-linux-x64` on VSC 1.86.0. Looks like it's [fixed](https://github.com/microsoft/debugpy/issues/1379) in `debugpy` 1.8.0?

**Comment by yoni-cmd** [comment]
I have tried upgrade to debug v2024.0.0.0 version. It doesn't work for me . And I also tried pre-release version, fail either. python debug extension version: ms-python.debugpy-2024.1.10362349-darwin-arm64
os: mac m1
python version: 3.8

**Comment by paulacamargo25** [comment]
Thanks for your issue report, as you can see, the error was on debugpy side. The error was fixed in the version 1.8.0. Currently our last version of the Python Debugger uses debugpy 1.7.0, in the next release we will update the version of debugpy.

**Comment by dorratz** [comment]
I have this issue too with the python debugger in Visual Studio Code - how can I solve it?

This is my environment:

OS name:Ubuntu 20.04.6 LTS
OS type: 64-bit

Visual studio code version:
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 5.15.0-94-generic

Python debugger version:v2024.0.0

This is the error I have in visual studio code:

cd /home/Documents/scripts2 ; /usr/bin/env /bin/python3 /home/ /.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 58729 -- /home/ /Documents/scripts2/print\ \(\"script\"\).py 
E+00000.030: Error while enumerating installed packages.
             
             Traceback (most recent call last):
               File "/home/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'
             
             Stack where logged:
               File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "/home/ /.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 91, in <module>
                 main()
               File "/home/ /.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 21, in main
                 log.describe_environment("debugpy.launcher startup environment:")
               File "/home/ /.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "/home/ /.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "/home/ /.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)

**Comment by Deretaz** [comment]
> Thanks for your issue report, as you can see, the error was on debugpy side. The error was fixed in the version 1.8.0. Currently our last version of the Python Debugger uses debugpy 1.7.0, in the next release we will update the version of debugpy.

As seen in the post above you, it will be fixed in the next version of debugpy. So update it via `pip` if available

**Comment by dorratz** [comment]
Thanks a lot, any expected date for the update?

**Comment by paulacamargo25** [comment]
Thanks for the bug report, the latest pre-released of the Python Debugger Extension now is using debugpy 1.8.1. Could you try with the version 2024.3.*? Thank you

**Comment by anthonykim1** [comment]
Just tried step item 1 and 2 from original TPI #141 I think it is working

**Comment by EeyoreLee** [comment]
@paulacamargo25 - hi, same situation but the latest prerelease version on my side is `v2024.1.10371006`.

**Comment by paulacamargo25** [comment]
could you try updating vscode?

**Comment by EeyoreLee** [comment]
@paulacamargo25 - Thanks, new version can be found after updating vscode.
