### ISSUE TITLE
Python Debugger show error messages while start debugging

### ISSUE THREAD

**Issue by Deretaz** [microsoft/vscode-python-debugger#195]
I get the following error while debugging python scripts on Windows (VSCode-x64-1.86.0)

Just updated Python Debugger Extension to v2024.0.0, before that, there was no such error

```
PS D:\Privat\Development\StreamDeck\Scripts>  & 'c:\Program Files\Python38\python.exe' 'c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '52492' '--' 'D:\Privat\Development\StreamDeck\Scripts\getCurrentDate.py' 
E+00000.047: Error while enumerating installed packages.

             Traceback (most recent call last):
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\common\log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'

             Stack where logged:
               File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher\__main__.py", line 91, in <module>
                 main()
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher\__main__.py", line 21, in main
                 log.describe_environment("debugpy.launcher startup environment:")
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\common\log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\common\log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\common\log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)


E+00000.015: Error while enumerating installed packages.

             Traceback (most recent call last):
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'

             Stack where logged:
               File "c:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "c:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
                 cli.main()
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 415, in main
                 api.ensure_logging()
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\api.py", line 61, in ensure_logging
                 log.describe_environment("Initial environment:")
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)


E+00000.156: Error while enumerating installed packages.

             Traceback (most recent call last):
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'

             Stack where logged:
               File "c:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "c:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
                 cli.main()
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
                 run()
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 281, in run_file
                 log.describe_environment("Pre-launch environment:")
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "c:\Users\Benja\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\common\log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)

```

That is the script that i debug currently

```
from datetime import date, timedelta
import win32clipboard as cb

def copy_to_clipboard(text_to_copy: str):
    if (len(text_to_copy) <= 0):
        return
    
    cb.OpenClipboard()
    cb.EmptyClipboard()
    cb.SetClipboardText(text_to_copy, cb.CF_UNICODETEXT)
    cb.CloseClipboard()
    
def paste_from_clipboard():
    cb.OpenClipboard()
    clipboardData = cb.GetClipboardData(cb.CF_UNICODETEXT)
    cb.CloseClipboard()
    return clipboardData
 

def get_date(days_delta: int=0, formated: bool=True):
    current_date = date.today()
    
    if (days_delta > 0):
        current_date = current_date + timedelta(days=days_delta)
    elif (days_delta < 0):
        current_date = current_date - timedelta(days=abs(days_delta))

    if (formated):
        current_date = current_date.strftime("%d.%m.%y")

    return current_date

dateValue = get_date()
copy_to_clipboard(dateValue)
```

**Comment by paulacamargo25** [comment]
Duplicated: https://github.com/microsoft/vscode-python-debugger/issues/143
