### ISSUE TITLE
Hitting `esc` when creating a python debug config still creates a debug config

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-python-debugger#223]
Testing #221

![Recording 2024-02-20 at 12 12 37](https://github.com/microsoft/vscode-python-debugger/assets/38270282/d89e13a4-a090-4e5f-9578-158b24c465d4)

**Comment by alexr00** [comment]
Also, that quick input doesn't say what should be entered.

**Comment by anthonykim1** [comment]
I was trying to verify this and suddenly started getting `FileNotFoundError` when I pressed ESC in the step like video. 
```
 /usr/bin/env /Users/anthonykim/Desktop/djangoExample/.venv/bin/p
ython /Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/deb
ugpy/adapter/../../debugpy/launcher 64791 -- /Users/anthonykim/Desktop/djangoExample/manage.py runserver 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
    with io_open_code(decoded_path) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anthonykim/Desktop/djangoExample/manage.py'
anthonykim@Anthonys-MacBook-Pro-2 djangoExample %  cd /Users/anthonykim/Desktop/djangoExample ; /usr/bin/env /Users
/anthonykim/Desktop/djangoExample/.venv/bin/python /Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-
2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher 64805 -- /Users/anthonykim/Desktop
/djangoExample/manage.py runserver 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
    with io_open_code(decoded_path) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anthonykim/Desktop/djangoExample/manage.py'
anthonykim@Anthonys-MacBook-Pro-2 djangoExample %  cd /Users/anthonykim/Desktop/djangoExample ; /usr/bin/env /Users
/anthonykim/Desktop/djangoExample/.venv/bin/python /Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-
2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher 64813 -- /Users/anthonykim/Desktop
/djangoExample/manage.py runserver 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
    with io_open_code(decoded_path) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anthonykim/Desktop/djangoExample/manage.py'
anthonykim@Anthonys-MacBook-Pro-2 djangoExample %  cd /Users/anthonykim/Desktop/djangoExample ; /usr/bin/env /Users
/anthonykim/Desktop/djangoExample/.venv/bin/python /Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-
2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher 64822 -- /Users/anthonykim/Desktop
/djangoExample/manage.py runserver 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
    with io_open_code(decoded_path) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anthonykim/Desktop/djangoExample/manage.py'
anthonykim@Anthonys-MacBook-Pro-2 djangoExample %  cd /Users/anthonykim/Desktop/djangoExample ; /usr/bin/env /Users
/anthonykim/Desktop/djangoExample/.venv/bin/python /Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-
2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher 64831 -- /Users/anthonykim/Desktop
/djangoExample/manage.py runserver 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
    with io_open_code(decoded_path) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anthonykim/Desktop/djangoExample/manage.py'
anthonykim@Anthonys-MacBook-Pro-2 djangoExample %  cd /Users/anthonykim/Desktop/djangoExample ; /usr/bin/env /Users
/anthonykim/Desktop/djangoExample/.venv/bin/python /Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-
2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher 64841 -- /Users/anthonykim/Desktop
/djangoExample/manage.py runserver 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/anthonykim/.vscode-insiders/extensions/ms-python.debugpy-2024.3.10521006-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
    with io_open_code(decoded_path) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anthonykim/Desktop/djangoExample/manage.py'
```

**Comment by rzhao271** [comment]
I can repro the original issue.
Will add the unreleased tag for now because I noticed the fix went in recently.
