### ISSUE TITLE
Cannot read properties of undefined (reading 'resolveEnvironment') 

### ISSUE THREAD

**Issue by hk0624** [microsoft/vscode-python-debugger#333]
VSCode 1.88.1
When Press F5 or Ctrl+F5，it pops up a message "Cannot read properties of undefined (reading 'resolveEnvironment') " and stop debug.

**Comment by blueardour** [comment]
same error on 1.83.1

**Comment by JianxiangL** [comment]
same error on 1.89.1

版本: 1.89.1 (user setup)
提交: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
日期: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by paulacamargo25** [comment]
Thanks for the bug report, could you share your configuration in the `launch.json` file? Thanks

**Comment by JianxiangL** [comment]
> 感谢您的错误报告，您能否在文件中分享您的配置？谢谢`launch.json`

{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: 当前文件",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
抱歉之前忽略了您的回复，这个问题我已经解决，方法就是重新安装配置了一下conda虚拟环境。

**Comment by paulacamargo25** [comment]
Could you try with using `type: "debugpy"` in your config? Thanks

**Comment by onahkenneth** [comment]
Same error on 1.92.2

Config in launch.json

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}`

**Comment by Josie-xufan** [comment]
same error on 1.92.2

Config in launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}

**Comment by onahkenneth** [comment]
@Josie-xufan 
Ensure you install debugpy module

**Comment by DINGdeZHENZ** [comment]
There is the same issue in VSC 1.95.2
I do not have any idea to solve it.


```
Version: 1.95.2 (user setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
```
Launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]
}
```
Log of Extension Host
```
2024-11-08 10:53:45.215 [error] TypeError: Cannot read properties of undefined (reading 'resolveEnvironment')
	at l (c:\Users\sys\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\dist\extension.js:2:835287)
	at async c:\Users\sys\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\dist\extension.js:2:905338
	at async Y0.h (file:///d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32825) debugpy.debugUsingLaunchConfig {"value":"ms-python.debugpy","_lower":"ms-python.debugpy"}
```


BTW, i'm using Conda to manage the project

**Comment by liesauer** [comment]
```
Version: 1.104.0 (user setup)
Commit: f220831ea2d946c0dcb0f3eaa480eb435a2c1260
Date: 2025-09-10T06:46:18.035Z
Electron: 37.3.1
ElectronBuildId: 12342881
Chromium: 138.0.7204.235
Node.js: 22.18.0
V8: 13.8.258.31-electron.0
OS: Windows_NT x64 10.0.26100
```

i don't know which one is broken, vsc or debugger?

i change `type` from `debugpy` back to `python`, and it works again...

**Comment by shatandv** [comment]
I have a very similar problem, so posting it here. For me it only happens on WSL2 Ubuntu 22.04 distro from a Win 11 host. I'm trying to launch debug on any python launch config and it immediately throws an error.

```
TypeError: Cannot read properties of undefined (reading 'getEnvironment')
    at f (/home/user/.vscode-server/extensions/ms-python.debugpy-2026.6.0-linux-x64/dist/extension.js:2:740148)
    at processTicksAndRejections (node:internal/process/task_queues:103:5)
    at p.resolveAndUpdatePythonPath (/home/user/.vscode-server/extensions/ms-python.debugpy-2026.6.0-linux-x64/dist/extension.js:2:792528)
    at p.resolveAndUpdatePaths (/home/user/.vscode-server/extensions/ms-python.debugpy-2026.6.0-linux-x64/dist/extension.js:2:792107)
    at p.resolveDebugConfiguration (/home/user/.vscode-server/extensions/ms-python.debugpy-2026.6.0-linux-x64/dist/extension.js:2:797069)
```

VSC version from Help->About
```
Version: 1.120.0 (user setup)
Commit: 0958016b2af9f09bb4257e0df4a95e2f90590f9f
Date: 2026-05-12T20:17:22Z
Electron: 39.8.8
ElectronBuildId: 13870025
Chromium: 142.0.7444.265
Node.js: 22.22.1
V8: 14.2.231.22-electron.0
OS: Windows_NT x64 10.0.26200
```

VSC version via `code --version` inside WSL distro
```
1.120.0
0958016b2af9f09bb4257e0df4a95e2f90590f9f
x64
```

launch.json sample that reproduces
```json
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python - Launch API",
			"type": "debugpy",
			"request": "launch",
			"module": "uvicorn",
			"args": [
				"api:app",
				"--reload",
				"--no-server-header",
				"--lifespan",
				"on",
				"--host",
				"0.0.0.0",
				"--port",
				"5000"
			],
			"cwd": "${workspaceFolder}/directory/src",
			"python": "${workspaceFolder}/directory/.venv/bin/python",
			"console": "integratedTerminal",
			"jinja": true,
			"justMyCode": true,
			// "envFile": "${workspaceFolder}/directory/.env.docker",
			"envFile": "${workspaceFolder}/directory/.env.local",
			// "envFile": "${workspaceFolder}/directory/.env.remote",
			"env": {
				"PYDEVD_DISABLE_FILE_VALIDATION": "1"
			}
		}
	]
}
```

After I restart extension host / reload window / reboot wsl it randomly gets fixed then breaks again. Feels similar to a race condition.

Would love to provide more info or help in any way.

**Comment by LDTips** [comment]
I have a similar issue, but instead with 'getEnvironment'. I did as liesauer wrote:
> i change type from `debugpy` back to `python`, and it works again...

and this fixed my issue
