### ISSUE TITLE
re-running a pytest test causes it to run all tests in the workspace

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode-python-debugger#338]
this started happening as of the latest vscode update (1.89.0)

to reproduce:

1. put a breakpoint in a pytest test
    ![image](https://github.com/microsoft/vscode-python-debugger/assets/57028336/7e29b79f-431a-4f88-a826-4186f40ec72b)
2. right click the run button and click "Debug test"
3. when it pauses on the breakpoint, click the restart button
    ![image](https://github.com/microsoft/vscode-python-debugger/assets/57028336/f83f02e8-9338-4096-ba3a-1255046534c2)
4. check the debug console
    ```
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
        return _run_code(code, main_globals, None,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
        exec(code, run_globals)
      File "c:\Users\user\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
        cli.main()
      File "c:\Users\user\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
        run()
      File "c:\Users\user\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
        runpy.run_path(target, run_name="__main__")
      File "c:\Users\user\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
        return _run_module_code(code, init_globals, run_name,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "c:\Users\user\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "c:\Users\user\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
        exec(code, run_globals)
      File "c:\Users\user\.vscode\extensions\ms-python.python-2024.6.0\python_files\vscode_pytest\run_pytest_script.py", line 62, in <module>
        test_ids_from_buffer = raw_json["params"]
                               ~~~~~~~~^^^^^^^^^^
    KeyError: 'params'
    ```

**Comment by alfonzso** [comment]
Workaround (till not fixed): install/downgrade ms-python.python == 2024.4.1 version.

**Comment by golgor** [comment]
Also started experiencing this. Thanks for the workaround @alfonzso!

**Comment by iiwolf** [comment]
This was driving me nuts and I couldn't find a thread on it! Can confirm that downgrading works

**Comment by eleanorjboyd** [comment]
Hello! We are aware of this issue and actively working to get a fix- apologies for the delay this ended up being a more complex fix than anticipated. Thanks

**Comment by DetachHead** [comment]
it seems like a recent update has changed the behavior. now instead of raising `KeyError`, it re-runs but it incorrectly attempts to run all tests in your project instead of the specific test you're trying to rerun

**Comment by golgor** [comment]
> it seems like a recent update has changed the behavior. now instead of raising `KeyError`, it re-runs but it incorrectly attempts to run all tests in your project instead of the specific test you're trying to rerun

I can confirm this. It is very annoying. 😞

**Comment by lanshenghai** [comment]
Not fixed until now?

**Comment by eleanorjboyd** [comment]
Hello! I am pretty sure we fixed this but please reopen if that is not the case- thanks!

**Comment by paul-voelker** [comment]
> @eleanorjboyd it's still broken, it still attempts to re-run every test in the project instead of whatever test(s) were selected as i mentioned [here](https://github.com/microsoft/vscode-python-debugger/issues/338#issuecomment-2244189177). can this issue be re-opened please? (it doesn't let me re-open it myself)
> 
> or would you rather i raise a new issue as the behavior has changed?

Same for me

**Comment by DetachHead** [comment]
works now, thanks!
