### ISSUE TITLE
Unable to attach to process on Linux

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-python-debugger#40]
Testing #35

1. Start a process that takes in input or a FastAPI server
2. Try attaching to it by selecting it after running the attach launch config
3. :bug: Unable to attach to the process

Debug console log (contains long lines)

```
Attach to PID failed.

--- Starting attach to pid: 37499 ---
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Inappropriate ioctl for device.
Target 'None' cannot support this command.
The target architecture is set to "auto" (currently "i386").
No symbol table is loaded.  Use the "file" command.
No symbol table is loaded.  Use the "file" command.
E+00000.133: Code injection into PID=37499 failed:
             
             Traceback (most recent call last):
               File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 391, in attach_to_pid
                 add_code_to_python_process.run_python_code(
               File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 471, in run_python_code_linux
                 subprocess.check_call(' '.join(cmd), shell=True, env=env)
               File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
                 raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command 'gdb --nw --nh --nx --pid 37499 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture auto' --eval-command='call (void*)dlopen("/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='sharedlibrary attach_linux_amd64' --eval-command='call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_dir = decode([47, 104, 111, 109, 101, 47, 112, 97, 114, 97, 108, 108, 101, 108, 115, 47, 46, 118, 115, 99, 111, 100, 101, 45, 105, 110, 115, 105, 100, 101, 114, 115, 47, 101, 120, 116, 101, 110, 115, 105, 111, 110, 115, 47, 109, 115, 45, 112, 121, 116, 104, 111, 110, 46, 100, 101, 98, 117, 103, 112, 121, 45, 50, 48, 50, 51, 46, 49, 46, 49, 49, 55, 52, 49, 48, 48, 56, 47, 98, 117, 110, 100, 108, 101, 100, 47, 108, 105, 98, 115, 47, 100, 101, 98, 117, 103, 112, 121, 47, 97, 100, 97, 112, 116, 101, 114, 47, 46, 46, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 115, 101, 114, 118, 101, 114]);setup = json.loads(decode([123, 34, 109, 111, 100, 101, 34, 58, 32, 34, 99, 111, 110, 110, 101, 99, 116, 34, 44, 32, 34, 97, 100, 100, 114, 101, 115, 115, 34, 58, 32, 91, 34, 49, 50, 55, 46, 48, 46, 48, 46, 49, 34, 44, 32, 53, 50, 54, 56, 49, 93, 44, 32, 34, 119, 97, 105, 116, 95, 102, 111, 114, 95, 99, 108, 105, 101, 110, 116, 34, 58, 32, 102, 97, 108, 115, 101, 44, 32, 34, 108, 111, 103, 95, 116, 111, 34, 58, 32, 110, 117, 108, 108, 44, 32, 34, 97, 100, 97, 112, 116, 101, 114, 95, 97, 99, 99, 101, 115, 115, 95, 116, 111, 107, 101, 110, 34, 58, 32, 34, 50, 56, 54, 102, 99, 51, 55, 97, 56, 52, 53, 53, 97, 50, 52, 101, 102, 50, 49, 53, 54, 51, 52, 55, 56, 49, 56, 98, 49, 51, 99, 48, 99, 54, 97, 99, 51, 50, 101, 101, 98, 98, 100, 54, 56, 101, 52, 99, 101, 102, 100, 99, 49, 50, 56, 56, 101, 97, 99, 100, 50, 99, 98, 52, 34, 125]));sys.path.insert(0, script_dir);import attach_pid_injected;del sys.path[0];attach_pid_injected.attach(setup);", 0)'' returned non-zero exit status 1.
             
             Stack where logged:
               File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
                 exec(code, run_globals)
               File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/__main__.py", line 39, in <module>
                 cli.main()
               File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 430, in main
                 run()
               File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 398, in attach_to_pid
                 log.reraise_exception("Code injection into PID={0} failed:", pid)
               File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/common/log.py", line 222, in reraise_exception
                 _exception(format_string, *args, **kwargs)
             

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 398, in attach_to_pid
    log.reraise_exception("Code injection into PID={0} failed:", pid)
  File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 391, in attach_to_pid
    add_code_to_python_process.run_python_code(
  File "/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 471, in run_python_code_linux
    subprocess.check_call(' '.join(cmd), shell=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gdb --nw --nh --nx --pid 37499 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture auto' --eval-command='call (void*)dlopen("/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='sharedlibrary attach_linux_amd64' --eval-command='call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_dir = decode([47, 104, 111, 109, 101, 47, 112, 97, 114, 97, 108, 108, 101, 108, 115, 47, 46, 118, 115, 99, 111, 100, 101, 45, 105, 110, 115, 105, 100, 101, 114, 115, 47, 101, 120, 116, 101, 110, 115, 105, 111, 110, 115, 47, 109, 115, 45, 112, 121, 116, 104, 111, 110, 46, 100, 101, 98, 117, 103, 112, 121, 45, 50, 48, 50, 51, 46, 49, 46, 49, 49, 55, 52, 49, 48, 48, 56, 47, 98, 117, 110, 100, 108, 101, 100, 47, 108, 105, 98, 115, 47, 100, 101, 98, 117, 103, 112, 121, 47, 97, 100, 97, 112, 116, 101, 114, 47, 46, 46, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 115, 101, 114, 118, 101, 114]);setup = json.loads(decode([123, 34, 109, 111, 100, 101, 34, 58, 32, 34, 99, 111, 110, 110, 101, 99, 116, 34, 44, 32, 34, 97, 100, 100, 114, 101, 115, 115, 34, 58, 32, 91, 34, 49, 50, 55, 46, 48, 46, 48, 46, 49, 34, 44, 32, 53, 50, 54, 56, 49, 93, 44, 32, 34, 119, 97, 105, 116, 95, 102, 111, 114, 95, 99, 108, 105, 101, 110, 116, 34, 58, 32, 102, 97, 108, 115, 101, 44, 32, 34, 108, 111, 103, 95, 116, 111, 34, 58, 32, 110, 117, 108, 108, 44, 32, 34, 97, 100, 97, 112, 116, 101, 114, 95, 97, 99, 99, 101, 115, 115, 95, 116, 111, 107, 101, 110, 34, 58, 32, 34, 50, 56, 54, 102, 99, 51, 55, 97, 56, 52, 53, 53, 97, 50, 52, 101, 102, 50, 49, 53, 54, 51, 52, 55, 56, 49, 56, 98, 49, 51, 99, 48, 99, 54, 97, 99, 51, 50, 101, 101, 98, 98, 100, 54, 56, 101, 52, 99, 101, 102, 100, 99, 49, 50, 56, 56, 101, 97, 99, 100, 50, 99, 98, 52, 34, 125]));sys.path.insert(0, script_dir);import attach_pid_injected;del sys.path[0];attach_pid_injected.attach(setup);", 0)'' returned non-zero exit status 1.
PYDEVD_GDB_SCAN_SHARED_LIBRARIES not set (scanning all libraries for needed symbols).
Running: gdb --nw --nh --nx --pid 37499 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture auto' --eval-command='call (void*)dlopen("/home/parallels/.vscode-insiders/extensions/ms-python.debugpy-2023.1.11741008/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='sharedlibrary attach_linux_amd64' --eval-command='call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_dir = decode([47, 104, 111, 109, 101, 47, 112, 97, 114, 97, 108, 108, 101, 108, 115, 47, 46, 118, 115, 99, 111, 100, 101, 45, 105, 110, 115, 105, 100, 101, 114, 115, 47, 101, 120, 116, 101, 110, 115, 105, 111, 110, 115, 47, 109, 115, 45, 112, 121, 116, 104, 111, 110, 46, 100, 101, 98, 117, 103, 112, 121, 45, 50, 48, 50, 51, 46, 49, 46, 49, 49, 55, 52, 49, 48, 48, 56, 47, 98, 117, 110, 100, 108, 101, 100, 47, 108, 105, 98, 115, 47, 100, 101, 98, 117, 103, 112, 121, 47, 97, 100, 97, 112, 116, 101, 114, 47, 46, 46, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 115, 101, 114, 118, 101, 114]);setup = json.loads(decode([123, 34, 109, 111, 100, 101, 34, 58, 32, 34, 99, 111, 110, 110, 101, 99, 116, 34, 44, 32, 34, 97, 100, 100, 114, 101, 115, 115, 34, 58, 32, 91, 34, 49, 50, 55, 46, 48, 46, 48, 46, 49, 34, 44, 32, 53, 50, 54, 56, 49, 93, 44, 32, 34, 119, 97, 105, 116, 95, 102, 111, 114, 95, 99, 108, 105, 101, 110, 116, 34, 58, 32, 102, 97, 108, 115, 101, 44, 32, 34, 108, 111, 103, 95, 116, 111, 34, 58, 32, 110, 117, 108, 108, 44, 32, 34, 97, 100, 97, 112, 116, 101, 114, 95, 97, 99, 99, 101, 115, 115, 95, 116, 111, 107, 101, 110, 34, 58, 32, 34, 50, 56, 54, 102, 99, 51, 55, 97, 56, 52, 53, 53, 97, 50, 52, 101, 102, 50, 49, 53, 54, 51, 52, 55, 56, 49, 56, 98, 49, 51, 99, 48, 99, 54, 97, 99, 51, 50, 101, 101, 98, 98, 100, 54, 56, 101, 52, 99, 101, 102, 100, 99, 49, 50, 56, 56, 101, 97, 99, 100, 50, 99, 98, 52, 34, 125]));sys.path.insert(0, script_dir);import attach_pid_injected;del sys.path[0];attach_pid_injected.attach(setup);", 0)'
```

**Comment by paulacamargo25** [comment]
The error is in debugpy side, refer to https://github.com/microsoft/debugpy/issues/1464
