### ISSUE TITLE
pydevd_sys_monitoring always throws TypeError

### ISSUE THREAD

**Issue by vegetablest** [microsoft/vscode-python-debugger#483]
After python debug was automatically updated to version v2024.12.0, this error was reported during debugging. When I rolled back to the previous version, it worked normally.

<details> <summary>Error message</summary>

```consol
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/starlette/routing.py", line 93, in app
    await func(session)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/venv/lib/python3.12/site-packages/fastapi/routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "/Users/suaofeng/VscodeProjects/tablegpt-slim-py/api/tablegpt/routers/chat.py", line 318, in handle_chat
    if not conv.title_generated:
           ^^^^
  File "<stringsource>", line 69, in cfunc.to_py.__Pyx_CFunc_7f6725__29_pydevd_sys_monitoring_cython_object__lParen__etc_to_py_4code_11from_offset_9to_offset.wrap
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 1367, in _pydevd_sys_monitoring_cython._jump_event
TypeError: an integer is required
```
</details>

**Comment by xidianzhangjun** [comment]
> After python debug was automatically updated to version v2024.12.0, this error was reported during debugging. When I rolled back to the previous version, it worked normally.
> 
> Error message
> ```
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
> ......
> cfunc.to_py.__Pyx_CFunc_7f6725__29_pydevd_sys_monitoring_cython_object__lParen__etc_to_py_4code_11from_offset_9to_offset.wrap
>   File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 1367, in _pydevd_sys_monitoring_cython._jump_event
> TypeError: an integer is required
> ```

Me too.
